class MyException() extends Exception {
  fun getMessage(): String {
    ""
  }
}

fun main(): void {
  print_raw(
    try {
      throw MyException()
    } catch {
    | MyException _ ->
      f = x -> {
        if (x == 0) {
          return "Pass\n"
        } else {
          return "Fail"
        }
      };
      f(0)
    | _ -> "Fail"
    }
  )
}
