class MyException() extends Exception {
  fun getMessage(): String {
    ""
  }
}

fun main(): void {
  print_raw(
    try {
      throw MyException()
    } catch {
    | MyException _ ->
      i = 0;
      while (i == 0) {
        break "Pass\n"
      } else "Fail"
    | _ -> "Fail"
    }
  )
}
